var product = [{
    "id": 0,
    "title": "",
    "price": "",
    "description": "",
    "brand": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png"
}, {
    "id": 1,
    "title": "Arduino UNO",
    "price": 24,
    "description": "The Arduino UNO R3 is the perfect board to get familiar with electronics and coding. This versatile development board is equipped with the well-known ATmega328P and the ATMega 16U2 Processor.This board will give you a great first experience within the world of Arduino.",
    "brand": "Arduino",
    "microcontroller": "ATmega328P",
    "operatingvoltage": "5V",
    "recomendetinputvoltage": "7-12V",
    "inputvoltagelimit": "6-20V",
    "digitaliopins": "14",
    "pwmiopins": "6",
    "analoginputpins": "6",
    "dccurrentperiopin": "20 mA",
    "currentpersmallpowerpin": "50 mA",
    "flashmemory": "32 KB (0.5 KB used by bootloader)",
    "sram": "2 KB",
    "eeprom": "1 KB",
    "clockspeed": "16 MHz",
    "size": "68.6mm*53.4mm*24.9mm",
    "weight": "25 g",
    "extrainformation": "--",
    "image": "https://store.arduino.cc/cdn/shop/products/A000066_03.front_643x483.jpg?v=1629815860"
}, {
    "id": 2,
    "title": "Arduino Mega",
    "price": 42,
    "description": "The Arduino Mega 2560 is a microcontroller board based on the ATmega2560. It has 54 digital input/output pins (of which 15 can be used as PWM outputs), 16 analog inputs, 4 UARTs (hardware serial ports), a 16 MHz crystal oscillator, a USB connection, a power jack, an ICSP header, and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started. The Mega 2560 board is compatible with most shields designed for the Uno and the former boards Duemilanove or Diecimila.",
    "brand": "Arduino",
    "microcontroller": "ATmega2560",
    "operatingvoltage": "5V",
    "recomendetinputvoltage": "7-12V",
    "inputvoltagelimit": "6-20V",
    "digitaliopins": "54",
    "pwmiopins": "15",
    "analoginputpins": "16",
    "dccurrentperiopin": "20 mA",
    "currentpersmallpowerpin": "50 mA",
    "flashmemory": "256 KB (8 KB used by bootloader)",
    "sram": "8 KB",
    "eeprom": "4 KB",
    "clockspeed": "16 MHz",
    "size": "101.52mm*53.3mm*20mm",
    "weight": "37 g",
    "extrainformation": "--",
    "image": "https://store.arduino.cc/cdn/shop/products/A000067_00.front_643x483.jpg?v=1637830343"
},
{
    "id": 3,
    "title": "Arduino Micro",
    "price": 21.60,
    "description": "The Arduino Micro is a microcontroller board based on the ATmega32U4. It has 20 digital input/output pins, 7 PWM channels, 12 analog input channels, and a 5V operating voltage. This board is recommended to be powered with an input voltage in the range of 7-12V. It comes with 32 KB of flash memory (4 KB used by the bootloader), 2.5 KB of SRAM, and 1 KB of EEPROM. The clock speed is 16 MHz, and it includes a built-in LED on pin 13. The board has dimensions of 48 mm x 18 mm and weighs 13 g.",
    "brand": "Arduino",
    "microcontroller": "ATmega32U4",
    "operatingvoltage": "5V",
    "recomendetinputvoltage": "7-12V",
    "inputvoltagelimit": "7-12V",
    "digitaliopins": "20",
    "pwmiopins": "7",
    "analoginputpins": "12",
    "dccurrentperiopin": "20 mA",
    "currentpersmallpowerpin": "50 mA",
    "flashmemory": "32 KB (4 KB used by bootloader)",
    "sram": "2.5 KB",
    "eeprom": "1 KB",
    "clockspeed": "16 MHz",
    "size": "48 mm x 18 mm",
    "weight": "13 g",
    "extrainformation": "--",
    "image": "https://store.arduino.cc/cdn/shop/products/A000053_03.front._643x483.jpg?v=1626444584"
},
{
    "id": 4,
    "title": "Arduino Nano",
    "price": 24.00,
    "description": "The Arduino Nano operates at 5V and features 32 KB of flash memory (2 KB used by the bootloader), 2 KB of SRAM, and a clock speed of 16 MHz. It has 8 analog input pins, 1 KB of EEPROM, and supports a maximum current of 20 mA per I/O pin. The recommended input voltage range is 7-12V. The board provides 22 digital I/O pins, including 6 PWM channels. It has 6 PWM outputs and consumes 19 mA of power. The PCB size is 18 mm x 45 mm, and the board weighs 7 g.",
    "brand": "Arduino",
    "microcontroller": "ATmega328",
    "operatingvoltage": "5V",
    "recomendetinputvoltage": "7-12V",
    "inputvoltagelimit": "7-12V",
    "flashmemory": "32 KB (2 KB used by bootloader)",
    "sram": "2 KB",
    "clockspeed": "16 MHz",
    "analoginputpins": "8",
    "eeprom": "1 KB",
    "dccurrentperiopin": "20 mA",
    "currentpersmallpowerpin": "50 mA",
    "inputvoltage": "7-12V",
    "digitaliopins": "22",
    "pwmiopins": "6",
    "pwmsupport": "6",
    "powerconsumption": "19 mA",
    "size": "18 mm x 45 mm",
    "weight": "7 g",
    "extrainformation": "--",
    "image": "https://store.arduino.cc/cdn/shop/products/A000005_03.front_643x483.jpg?v=1628695103"
}
,
{
    "id": 5,
    "title": "Arduino Due",
    "price": 40.80,
    "description": "The board contains everything needed to support the microcontroller; simply connect it to a computer with a micro-USB cable or power it with a AC-to-DC adapter or battery to get started. The Due is compatible with all Arduino shields that work at 3.3V and are compliant with the 1.0 Arduino pinout.",
    "brand": "Arduino",
    "microcontroller": "AT91SAM3X8E",
    "operatingvoltage": "3.3V",
    "recomendetinputvoltage": "7-12V",
    "inputvoltagelimit": "6-16V",
    "digitaliopins": "54",
    "pwmiopins": "12",
    "analoginputpins": "12",
    "dccurrentperiopin": "--",
    "currentpersmallpowerpin": "800 mA",
    "flashmemory": "512 KB",
    "sram": "96 KB (64KB + 32KB)",
    "eeprom": "--",
    "clockspeed": "84 MHz",
    "size": "101.52 mm x 53.3 mm",
    "weight": "36 g",
    "extrainformation": "2 DAC Pins, Maximum 130mA of current on all power lines",
    "image": "https://store.arduino.cc/cdn/shop/products/A000056_03.front_643x483.jpg?v=1626444750"
}, {
    "id": 6,
    "title": "Arduino UNO SMD",
    "price": 24,
    "description": "The Arduino UNO R3 is the perfect board to get familiar with electronics and coding. This versatile development board is equipped with the well-known ATmega328P and the ATMega 16U2 Processor.This board will give you a great first experience within the world of Arduino.",
    "brand": "Arduino",
    "microcontroller": "ATmega328P",
    "operatingvoltage": "5V",
    "recomendetinputvoltage": "7-12V",
    "inputvoltagelimit": "6-20V",
    "digitaliopins": "14",
    "pwmiopins": "6",
    "analoginputpins": "6",
    "dccurrentperiopin": "20 mA",
    "currentpersmallpowerpin": "50 mA",
    "flashmemory": "32 KB (0.5 KB used by bootloader)",
    "sram": "2 KB",
    "eeprom": "1 KB",
    "clockspeed": "16 MHz",
    "size": "68.6mm*53.4mm*24.9mm",
    "weight": "25 g",
    "extrainformation": "",
    "image": "https://store.arduino.cc/cdn/shop/products/A000073_00.front_643x483.jpg?v=1637829596"
}, {
    "id": 7,
    "title": "Arduino MKR WiFi 1010",
    "price": 33.50,
    "description": "The Arduino MKR WiFi 1010 is the easiest point of entry to basic IoT and pico-network application design. Whether you are looking at building a sensor network connected to your office or home router, orif you want to create a Bluetooth® Low Energy device sending data to a cellphone, the MKR WiFi 1010 is your one-stop-solution for many of the basic IoT application scenarios.",
    "brand": "Arduino",
    "microcontroller": "SAMD21 Cortex®-M0+ 32bit low power ARM® MCU",
    "operatingvoltage": "3.3V",
    "recomendetinputvoltage": "5V (USB/VIN)",
    "inputvoltagelimit": "5V",
    "digitaliopins": "8",
    "pwmiopins": "13",
    "analoginputpins": "7",
    "dccurrentperiopin": "7 mA",
    "currentpersmallpowerpin": "--",
    "flashmemory": "256 KB (internal)",
    "sram": "32 KB",
    "eeprom": "--",
    "clockspeed": "32.768 kHz (RTC), 48 MHz",
    "size": "61.5mm*25mm",
    "weight": "32 g",
    "extrainformation": "ATECC508 Secure Element, 1s Lipo 3.7V Battery Connection (Minimum 1024mAh), 1*UART, 1*SPI, 1*I2C, 1*DAC",
    "image": "https://store.arduino.cc/cdn/shop/products/ABX00023_03.front_9546fc94-9608-4ee8-94f4-62165312aa32_643x483.jpg?v=1630488949"
}, {
    "id": 8,
    "title": "Potenta H7",
    "price": 99,
    "description": "Portenta H7 allows you to build your next smart project. Ever wanted an automated house? Or a smart garden? Well, now it’s easy with the Arduino IoT Cloud compatible boards. It means: you can connect devices, visualize data, control and share your projects from anywhere in the world. Whether you’re a beginner or a pro, we have a wide range of plans to make sure you get the features you need.",
    "brand": "Arduino-Pro",
    "microcontroller": "STM32H747XI dual Cortex®-M7+M4 32bit low power Arm® MCU",
    "operatingvoltage": "3.3V",
    "recomendetinputvoltage": "5V (USB/VIN)",
    "inputvoltagelimit": "5V",
    "digitaliopins": "84",
    "pwmiopins": "10",
    "analoginputpins": "8",
    "dccurrentperiopin": "--",
    "currentpersmallpowerpin": "--",
    "flashmemory": "2 MB",
    "sram": "1 MB",
    "eeprom": "--",
    "clockspeed": "480MHz",
    "size": "66mm*25mm",
    "weight": "--",
    "extrainformation": "NXP SE0502 Secure Element, 1s Lipo 3.7V Battery Connection (Minimum 700mAh, Integrated charger), MIPI DSI host & MIPI D-PHY, Chrom-ART graphical hardware Accelerator™ GPU, 22 Timers, 4*UART Ports(2* with flow controll), 10Mbps Ethernet, -40 °C to +85 °C operating temperature, two 80-Pin connectors, 8-bit Camera Interface (up to 80MHz), 3*ADC, 2*12-bit DAC, USB_C Connector",
    "image": "https://store.arduino.cc/cdn/shop/products/ABX00042_02.front_643x483.jpg?v=1675840144"
}, {
    "id": 9,
    "title": "Arduino MKR WAN 1300",
    "price": 42,
    "description": "Arduino MKR WAN 1300 has been designed to offer a practical and cost effective solution for makers seeking to add LoRa® connectivity to their projects with minimal previous experience in networking. It is based on the Atmel SAMD21 and a Murata  CMWX1ZZABZ Lo-Ra module.",
    "brand": "Arduino",
    "microcontroller": "SAMD21 Cortex-M0+ 32bit low power ARM® MCU",
    "operatingvoltage": "3.3V",
    "recomendetinputvoltage": "5V (USB/VIN)",
    "inputvoltagelimit": "5V",
    "digitaliopins": "8",
    "pwmiopins": "12",
    "analoginputpins": "7",
    "dccurrentperiopin": "7 mA",
    "currentpersmallpowerpin": "--",
    "flashmemory": "256 MB",
    "sram": "32 MB",
    "eeprom": "--",
    "clockspeed": "32.768 kHz (RTC), 48 MHz",
    "size": "67.64mm*25mm",
    "weight": "32 g",
    "extrainformation": "1*UART, 1*SPI, 1*I2C, 1*DAC, 8*External Interrupts, 2dB Antenna Power, 433/868/915 MHz Carrier frequency, Works in EU/US, CMWX1ZZABZ RAdio Module",
    "image": "https://store.arduino.cc/cdn/shop/products/MKRWAN1300WANT_03.front_643x483.jpg?v=1626953592"
}, {
    "id": 10,
    "title": "Potenta H7 Lite",
    "price": 66,
    "description": "The Portenta H7 Lite is a cost-effective solution, designed for complex environments where radio communication is not suitable or possible. It is perfect for developers who want to leverage the computational power of the Portenta H7, without the need for video output or advanced security features. The Portenta H7 Lite simultaneously runs high-level code and real-time tasks thanks to its two processors. For example, it can execute Arduino-compiled and MicroPython code at the same time, and have the two cores communicate with one another.",
    "brand": "Arduino-Pro",
    "microcontroller": "STM32H747XI dual Cortex®-M7+M4 32bit low power Arm® MCU",
    "operatingvoltage": "3.3V",
    "recomendetinputvoltage": "5V (USB/VIN)",
    "inputvoltagelimit": "5V",
    "digitaliopins": "84",
    "pwmiopins": "10",
    "analoginputpins": "8",
    "dccurrentperiopin": "--",
    "currentpersmallpowerpin": "--",
    "flashmemory": "2 MB",
    "sram": "1 MB",
    "eeprom": "--",
    "clockspeed": "480MHz",
    "size": "66mm*25mm",
    "weight": "--",
    "extrainformation": "Microchip ATECC608 Secure Element, 1s Lipo 3.7V Battery Connection (Minimum 700mAh, Integrated charger), 22 Timers, 4*UART Ports(2* with flow controll), 10Mbps Ethernet, -40 °C to +85 °C operating temperature, 8-bit Camera Interface (up to 80MHz), 3*ADC, 2*12-bit DAC, USB_C Connector",
    "image": "https://store.arduino.cc/cdn/shop/products/ABX00045_02.front_643x483.jpg?v=1630411591"
}]